spring:
  datasource:
    username: root
    password: M2575052366
    url: jdbc:mysql://localhost:3306/knowledge_planet?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis:
  type-aliases-package: com.major.knowledgePlanet.entity
  mapper-locations: classpath:mapping/*.xml
server:
  IP: 49.235.232.7
  port: 81
  servlet:
    context-path: /kp
user:
  defaultAvatar: http://localhost:8080/easyLab/static/student/avatar/defaultAvatar.jpg
logging:
  level:
    root: info
  file:
    name: /home/mengfanlin/package/knowledgePlanet/knowledgePlanet.log
saltValue: 1234