spring:
  datasource:
    username: root
    password: *
    url: jdbc:mysql://*:3306/knowledge_planet?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: *
    port: 6379
    password: *
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis:
  type-aliases-package: com.major.knowledgePlanet.entity
  mapper-locations: classpath:mapping/*.xml
server:
  IP: *
  port: 83
  servlet:
    context-path: /kp
logging:
  level:
    root: info
  file:
    name: /home/mengfanlin/package/knowledgePlanet/knowledgePlanet.log
swagger:
  enable: true
  applicationName: knowledgePlanet
  applicationVersion: 1.0
  applicationDescription: knowledgePlanet api info
saltValue: 1234
defaultAvatar: *
defaultPlanetAvatar: *
defaultCompetitionAvatar: *
defaultPlanetMaxNumber: 500